return {
  "utilyre/barbecue.nvim",
  create_autocmd = false,
  name = "barbecue",
  event = { "BufReadPost", "BufNewFile", "BufWritePre" },
  version = "*",
  dependencies = {
    "SmiteshP/nvim-navic",
    "nvim-tree/nvim-web-devicons", -- optional dependency
  },
  opts = {
    attach_navic = true,
    show_modified = true,
    show_dirname = false,
    theme = "auto",
    symbols = {
      ellipsis = "…",
    },
    kinds = {
      Array = "",
      Boolean = "",
      Class = "",
      Color = "",
      Constant = "",
      Constructor = "",
      Enum = "",
      EnumMember = "",
      Event = "",
      Field = "",
      File = "󰈙",
      Folder = "",
      Function = "",
      Interface = "",
      Key = "",
      Keyword = "",
      Method = "",
      Module = "",
      Namespace = "",
      Null = "",
      Number = "",
      Object = "",
      Operator = "",
      Package = "",
      Property = "",
      Reference = "",
      Snippet = "",
      String = "",
      Struct = "",
      Text = "",
      TypeParameter = "",
      Unit = "",
      Value = "",
      Variable = "",
    },
  },
  config = function(_, opts)
    require("barbecue").setup(opts)
  end,
}
